### ISSUE TITLE
license

### ISSUE THREAD

**Issue by Mazuco** [ArjunAranetaCodes/MoreCodes-Youtube#13]
please, put a license?

**Comment by ArjunAranetaCodes** [comment]
what license are you asking about?

**Comment by Mazuco** [comment]
A license in this repository? Is MIT? GNU? https://choosealicense.com/

**Comment by ArjunAranetaCodes** [comment]
Right. Just created an MIT for this one.
https://github.com/ArjunAranetaCodes/MoreCodes-Youtube/blob/master/LICENSE

**Comment by ArjunAranetaCodes** [comment]
Closing this one. License file has been created.

**Comment by Mazuco** [comment]
yes, thanks very much
